// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT158_2_API.Models;

public partial class TPackageCart
{
    public int PackageCartId { get; set; }

    public int? MemberId { get; set; }

    public int? PackageId { get; set; }

    public int? Qty { get; set; }

    public virtual TMember? Member { get; set; }

    public virtual TAllPackage? Package { get; set; }
}