// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT158_2_API.Models;

public partial class TPay
{
    public int PayId { get; set; }

    public int? OrderId { get; set; }

    public int? PayTypeId { get; set; }

    public decimal? Amount { get; set; }

    public virtual TPayType PayType { get; set; }
}